// TIMER ACTION TYPES
export const UPDATE_TIME = "UPDATE_TIME";

// STATUS ACTION TYPES
export const SET_IS_COUNTDOWN_ACTIVE = "SET_IS_COUNTDOWN_ACTIVE";
export const SET_IS_COUNTDOWN_RUNNING = "SET_IS_COUNTDOWN_RUNNING";

// INFO ACTION TYPES
export const SET_INFO_TEXT = "SET_INFO_TEXT";
export const CLEAR_INFO_TEXT = "CLEAR_INFO_TEXT";
