// TIMER ACTION TYPES
export const UPDATE_TIME = "UPDATE_TIME"

// STATUS ACTION TYPES
export const SET_IS_COUNTDOWN_ACTIVE = "SET_IS_COUNTDOWN_ACTIVE"
export const SET_IS_COUNTDOWN_RUNNING = "SET_IS_COUNTDOWN_RUNNING"